import sqlite3


db = sqlite3.connect("Example.db")
cursor = db.cursor()
try:
    cursor.execute("DROP TABLE IF EXISTS `Example` ")
    cursor.execute("CREATE TABLE `Example`(`ФИО студента` TEXT, `Город` VARCHAR(20),`Страна` VARCHAR(20), `Дата рожденья` MEDIUMINT DATE,`Электронный адрес` VARCHAR (20),`Контактный телефон` INTEGER,`Название группы` VARCHAR (20),`Средняя оценка` MEDIUMINT,`Предмета`VARCHAR (20), `Минимальная оценка`TINYINT, `Максимальная оценка`TINYINT)")

    cursor.execute("""INSERT INTO `Example` VALUES("Анянова Марина Игоревна","Канберра","Австралия","1986.06.15","****@gmail.com",096556480,"Intellias",12,"архитектура",5,11)""")
    cursor.execute("""INSERT INTO `Example` VALUES("Байгужина Лилия Робертовна ","Австрия","Вена","1996.01.11"," ****@gmail.com",096331480,"N-iX",10,"алгоритмы и структуры данных",2,10)""")
    cursor.execute("""INSERT INTO `Example` VALUES("Богапова Анастасия Валерьевна","Азербайджан","Баку","1990.06.25"," ****@gmail.com",096555670,"Genesis",11,"математическая статистика",6,9) """)
    cursor.execute("""INSERT INTO `Example` VALUES("Волков Максим Юрьевич","Албания","Тирана", "1996.12.05"," ****@gmail.com",096556357,"Sigma Software",8,"методы вычислений",1,9) """)
    cursor.execute("""INSERT INTO `Example` VALUES("Деткина Валерия Олеговна","Алжир","Алжир", "1990.06.10"," ****@gmail.com",096556851,"ELEKS",10,"компьютерные сети",9,11) """)
    cursor.execute("""INSERT INTO `Example` VALUES("Ерышева Анастасия Андреевна ","Ангола","Луанда", "1996.09.12"," ****@gmail.com",096556753,"DataArt",7,"анализ данных",4,9) """)
    cursor.execute("""INSERT INTO `Example` VALUES("Ефимов Дмитрий Борисович","Андорра","Андорра-ла-Велья", "2000.06.29"," ****@gmail.com",096556951,"ZONE3000",8,"теория игр",7,10) """)
    cursor.execute("""INSERT INTO `Example` VALUES("Жигульская Мария Сергеевна","Антигуа и Барбуда","Сент-Джонс", "1997.10.15"," ****@gmail.com",096556743,"Grid Dynamics",8,"методы оптимизации",5,9) """)
    cursor.execute("""INSERT INTO `Example` VALUES("Каканов Евгений Дмитриевич ","Аргентина","Буэнос-Айрес", "1992.02.07"," ****@gmail.com", 096556982 , "SoftServe", 8,"защита информации",2,7) """)
    cursor.execute("""INSERT INTO `Example` VALUES("Карпич Юлия Владимировна","Армения","Ереван", "1999.08.22"," ****@gmail.com", 096556957 , "Ciklum", 6,"теория программирования",6,9) """)
    cursor.execute("""INSERT INTO `Example` VALUES("Катерина Инна Александровна ","Афганистан","Кабул", "1995.01.04"," ****@gmail.com", 096556153 , "GlobalLogic", 9, "теория графов ", 3, 8) """)
    cursor.execute("""INSERT INTO `Example` VALUES("Клемешов Артем Сергеевич ","Багамские острова","Нассау", "1991.07.17"," ****@gmail.com", 096556228 , "Luxoft", 10, "теория управления", 5, 10) """)
    cursor.execute("""INSERT INTO `Example` VALUES("Корсун Вадим Артурович","Бангладеш","Дакка", "2005.01.01"," ****@gmail.com", 096556195 , "Infopulse",8, "алгебра и геометрия", 8, 12) """)

    print("Отображение всей информации из таблицы со студентами и оценками")
    cursor.execute("SELECT * FROM `Example`")
    print(cursor.fetchall())
    print("\n")
    print("Отображение ФИО всех студентов")
    cursor.execute("SELECT `ФИО студента` FROM `Example`")
    print(cursor.fetchall())
    print("\n")
    print("Отображение всех средних оценок")
    cursor.execute("SELECT `Средняя оценка` FROM `Example`")
    print(cursor.fetchall())
    print("\n")
    print("Показать ФИО всех студентов с минимальной оценкой, больше, чем указанная")
    cursor.execute("SELECT `ФИО студента`,`Минимальная оценка` FROM `Example`")
    print(cursor.fetchall())
    print("\n")
    print("Показать страны студентов. Названия стран должны быть уникальными")
    cursor.execute("SELECT `Страна` FROM `Example`")
    print(cursor.fetchall())
    print("\n")
    print("Показать города студентов. Названия городов должны быть уникальными")
    cursor.execute("SELECT `Город` FROM `Example`")
    print(cursor.fetchall())
    print("\n")
    print("Показать названия групп. Названия групп должны быть уникальными")
    cursor.execute("SELECT `Название группы` FROM `Example`")
    print(cursor.fetchall())
    print("\n")
    print("Показать название всех предметов с минимальными средними оценками. Названия предметов должны быть уникальными.")
    cursor.execute("SELECT `Предмета`, `Минимальная оценка`FROM `Example` WHERE `Минимальная оценка` > 0 ORDER BY `Минимальная оценка`")
    print(cursor.fetchall())
    print("\n")
    db.commit()
except sqlite3.Error as e:
    print(f"SQL---Error {e}")
finally:
    if cursor:
        cursor.close()
    if db:
        db.close()